Sprint 4: 4-LoginSignupValidation-GreydonOKeefe
oliviasl/We-Are-GAME pull request #39
Opened 2024-02-01 20:26 UTC by mcho9434

New Changes:
- Toasts for a variety of actions
- new userByEmail endpoint

2024-02-01 20:27 UTC, mcho9434 commented
@oliviasl 
Submitting for Greydon

2024-02-01 23:09 UTC, oliviasl commented on client/src/routes/HomePage.tsx
> +      email: email,
I'm getting a JSON formatting error here so there might be something weird going on with the info getting passed in

2024-02-01 23:09 UTC, oliviasl commented on client/src/routes/HomePage.tsx
> +    if (status <= 0) {
The status is returned in the format [user_id, user_status] so you may need to use something like status[1] <= 0 instead

2024-02-01 23:11 UTC, oliviasl requested changes
Good work so far! The toasts function perfectly but they don't match the styles right now, could you try to override some of the react toast styles? Also I left some comments on the code because the toast for unauthorized users doesn't work for me right now, so please take a look at that too.

2024-02-02 00:02 UTC, mcho9434 commented
@greydonokeefe Wanna take a look and lmk?

2024-02-06 19:57 UTC, mcho9434 commented
@oliviasl

2024-02-09 05:25 UTC, closed without merging